# @package _global_
defaults:
  - ziz
  
n_jobs: 8
num_gpus: 1

hydra:
  additional_parameters: {
      "clusters": "srf_gpu_01",
      "wckey": "wck_${oc.env:USER}",
      "gres": "gpu:${num_gpus}",
      # "exclude": "zizgpu03.cpu.stats.ox.ac.uk,zizgpu05.cpu.stats.ox.ac.uk"
      # "nodelist": "zizgpu02.cpu.stats.ox.ac.uk"
      # "nodelist": "zizgpu04.cpu.stats.ox.ac.uk"
      "nodelist": "zizgpu02.cpu.stats.ox.ac.uk"
    }
