# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

num_workers: 8

paths:
  experiments: results

data_dir: /data/localhost/not-backed-up/datasets-ziz-all/

hydra:
  sweep:
    dir: ./${paths.experiments}/${name}/${hydra.job.override_dirname}
    subdir: ${seed}
    # subdir: ${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}_${seed}
  run:
    dir: ./${paths.experiments}/${name}/${hydra.job.override_dirname}/${seed}
    # dir: ./${paths.experiments}/${name}/${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}_${seed}

  job_logging:
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'
    handlers:
      file:
        filename: run.log
    root:
      handlers: [console, file]

  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        exclude_keys: [name, experiment, server, seed, run, resume, num_workers, num_gpus, val_freq, logger, mode]

  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 840
    cpus_per_task: ${num_gpus}
    tasks_per_node: 1
    mem_gb: ${eval:126//8*${num_gpus}}
    name: ${hydra.job.name}
    partition: ziz-gpu
    max_num_timeout: 0
    array_parallelism: 32
    setup: ["export XLA_FLAGS='--xla_gpu_cuda_data_dir=/opt/cuda'", "export PATH=/opt/cuda/bin/:$PATH", "export LD_LIBRARY_PATH=/opt/cuda-10.2/lib64:$LD_LIBRARY_PATH", "export XLA_PYTHON_CLIENT_PREALLOCATE=false"]
    executable: /data/ziz/not-backed-up/${oc.env:USER}/${PROJECT_NAME}/venv/bin/python
    additional_parameters: {
      "wckey": "bigbayes_project",
      "gres": "gpu:${num_gpus}",
      # "nodelist": ["zizgpu01.cpu.stats.ox.ac.uk", "zizgpu03.cpu.stats.ox.ac.uk", "zizgpu04.cpu.stats.ox.ac.uk"],
      }

num_gpus: 1