defaults:
  # GENERAL #
  - _self_
  # - user

  - server: local_ziz
  - experiment: s2_toy

  # - callbacks: wandb # set this to null if you don't want to use callbacks
  - logger: all
  # - checkpoint: val_loss

  - optim: adam
  - scheduler: rcosine
  
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

now: ${now:%Y-%m-%d}/${now:%H-%M-%S}

resume: false
mode: all
seed: 0
PROJECT_NAME: score-sde
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/
ckpt_dir: ckpt
logs_dir: logs

logdir: ${work_dir}/results
# rundir: ${dataset.name}/${model.name}