defaults:
  # GENERAL #
  - _self_
  # - user

  - server: base_ziz
  - experiment: s2_toy

  # - callbacks: wandb # set this to null if you don't want to use callbacks
  # - logger: wandb # set logger here or use command line (e.g. `python run.py logger=wandb`)
  # - hydra: default
  # - checkpoint: val_loss

  - optim: adam
  - scheduler: rcosine

  - job
  - launcher: local

  # enable color logging
  - override hydra/launcher: submitit_local
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

now: ${now:%Y-%m-%d}/${now:%H-%M-%S}

seed: 0
PROJECT_NAME: score_sde
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/
ckpt_dir: ckpt

logdir: ${work_dir}/results
# rundir: ${dataset.name}/${model.name}